language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "8"

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn coveralls

branches:
  only:
  - master
  - staging