#%RAML 1.0
title: Rangle's Backend Starter
baseUri: https://api-koa-starter.rangleapp.io
mediaType: application/json
securitySchemes:
  none:
    type: x-none
    description: |
      Application currently does not include any authentication.
/auth: !include src/routes/auth/auth.raml
/push: !include src/routes/push/push.raml
